import { Metadata } from "next";

import HeroSection from "@/components/home/hero-section";
import DaftarFiturSection from "@/components/home/daftar-fitur-section";

export const metadata: Metadata = {
  title: "AllStarHub | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HeroSection />
      <DaftarFiturSection />
    </>
  );
}
