import { Metadata } from "next";

import HeroSection from "@/components/home/hero-section";
import FiturListSection from "@/components/home/fitur-list-section";

export const metadata: Metadata = {
  title: "AllStarHub | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HeroSection />
      <FiturListSection />
    </>
  );
}
