import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AllStarHub | About Us",
  description: "Generated by create next app",
};

const page = () => {
  return <>page</>;
};

export default page;
