import HeroSection from "@/components/about/hero-section";
import IntroSection from "@/components/about/intro-section";
import MissionSection from "@/components/about/mission-section";
import TeamSection from "@/components/about/team-section";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AllStarHub | About Us",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <HeroSection />
      <IntroSection />
      <MissionSection />
      <TeamSection />
    </>
  );
};

export default page;
