import Section404 from "@/components/not-found/section404";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AllStarHub | 404",
  description: "Generated by create next app",
};

export default function NotFound() {
  return (
    <>
      <Section404 />
    </>
  );
}
