import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AllStarHub | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return <div className="mt-80 h-full w-full bg-red-800">kk</div>;
}
